-- BATCH_STEP_EXECUTION_CONTEXT 삭제
DELETE FROM BATCH_STEP_EXECUTION_CONTEXT;

-- BATCH_STEP_EXECUTION 삭제
DELETE FROM BATCH_STEP_EXECUTION;

-- BATCH_JOB_EXECUTION_CONTEXT 삭제
DELETE FROM BATCH_JOB_EXECUTION_CONTEXT;

-- BATCH_JOB_EXECUTION_PARAMS 삭제
DELETE FROM BATCH_JOB_EXECUTION_PARAMS;

-- BATCH_JOB_EXECUTION 삭제
DELETE FROM BATCH_JOB_EXECUTION;

-- BATCH_JOB_INSTANCE 삭제
DELETE FROM BATCH_JOB_INSTANCE;
