-- 실행 중인 잡 실행을 삭제
DELETE FROM BATCH_STEP_EXECUTION_CONTEXT WHERE STEP_EXECUTION_ID IN (
    SELECT STEP_EXECUTION_ID FROM BATCH_STEP_EXECUTION WHERE JOB_EXECUTION_ID IN (
        SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE STATUS = 'STARTED'
    )
);

DELETE FROM BATCH_STEP_EXECUTION WHERE JOB_EXECUTION_ID IN (
    SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE STATUS = 'STARTED'
);

DELETE FROM BATCH_JOB_EXECUTION_CONTEXT WHERE JOB_EXECUTION_ID IN (
    SELECT JOB_EXECUTION_ID FROM BATCH_JOB_EXECUTION WHERE STATUS = 'STARTED'
);

DELETE FROM BATCH_JOB_EXECUTION WHERE STATUS = 'STARTED';
